select *from gold.dim_customers
select *from gold.dim_products
select *from gold.fact_sales


--1.  Database Exploration
select *from INFORMATION_SCHEMA.TABLES

select *from INFORMATION_SCHEMA.COLUMNS

select *from INFORMATION_SCHEMA.COLUMNS
where table_name = 'dim_cutomers'


--2.  Dimensions Exploration
select distinct country from gold.dim_customers

select distinct category from gold.dim_products

select distinct category,subcategory,product_name from gold.dim_products
order by 1,2,3


--3.   Date Exploration
select 
	min(order_date) as first_order_date,
	max(order_date) as last_order_date,
	datediff(year,min(order_date),max(order_date)) as order_range_years,
	datediff(month,min(order_date),max(order_date)) as order_range_months
from gold.fact_sales

select 
	min(birthdate) as oldest_birthdate,
	datediff(year,min(birthdate),getdate()) as oldest_age,
	max(birthdate) as youngest_birthdate,
	datediff(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customers


--4. Measures Exploration

-- Find the Total Sales
-- Find how many items are sold
-- Find the average selling price
-- Find the Total number of Orders
-- Find the total number of products
-- Find the total number of customers
-- Find the total number of customers that has placed an order

select  'Total Sales' as measure_name,sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total quantity', count(quantity) from gold.fact_sales
union all 
select 'Average price', avg(price) from gold.fact_sales
union all
select 'Total orders', count(distinct order_number) from gold.fact_sales
union all
select 'Total products', count(distinct product_name) from gold.dim_products
union all
select 'Total customers', count(customer_key) from gold.dim_customers
union all
select 'Total no cust placed order',count(distinct customer_key) from gold.fact_sales

--5.  Magnitude
-- Find total customers by countries
select 
	country,
	count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Find total customers by gender
select 
	gender,
	count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category
select 
	category,
	count(product_key) as total_product
from gold.dim_products
group by category
order by total_product desc

-- What is the average costs in each category?
select 
	category,
	avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc


-- What is the total revenue generated for each category?
select
	p.category,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.category
order by total_revenue desc

-- What is the total revenue generated by each customer?
select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_customer
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_customer desc

-- What is the distribution of sold items across countries?
select
	c.country,
	sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc 


--6.  Ranking
-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking
select top 5
	p.product_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue desc


-- Complex but Flexibly Ranking Using Window Functions
select *
from (
select 
	p.product_name,
	sum(f.sales_amount) as total_revenue,
	rank() over(order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
) as t
where rank_products <= 5





-- What are the 5 worst-performing products in terms of sales?
select top 5
	p.product_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue 
-- Find the top 10 customers who have generated the highest revenue
select top 10
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

-- The 3 customers with the fewest orders placed
select top 3
	c.customer_key,
	c.first_name,
	c.last_name,
	count(distinct f.order_number) as total_order
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_order


--7.  Change Over Time Analysis
-- Analyse sales performance over time
-- Quick Date Functions
select 
	year(order_date),
	sum(sales_amount)
from gold.fact_sales
where order_date is not null
group by year(order_date)
order by year(order_date)


select 
	year(order_date) as order_year,
	month(order_date) as order_month,
	sum(sales_amount) as total_sales,
	count(distinct customer_key) as total_customer,
	sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by year(order_date),month(order_date)
order by year(order_date),month(order_date)

-- DATETRUNC()
datetrunc(month,order_date) as order_date

-- FORMAT()
format(order_date,'yyyy-MMM') as order_date


--8.  Cumulative Analysis
-- Calculate the total sales per month 
-- and the running total of sales over time 

-- step 1
select
	order_date,
	sales_amount
from gold.fact_sales

-- step 2
select 
	datetrunc(month,order_date),
	sum(sales_amount)
from gold.fact_sales
where order_date is not null
group by datetrunc(month,order_date)
order by datetrunc(month,order_date)

-- step 3
select
	order_date,total_sales
from (
select 
	datetrunc(year,order_date) as order_date,
	sum(sales_amount) as total_sales
from gold.fact_sales
where order_date is not null
group by datetrunc(year,order_date)
--order by datetrunc(month,order_date)
)t
order by total_sales

-- step 4
select
	order_date,
	total_sales,
	sum(total_sales) over(order by order_date) as running_total_sales
from (
select 
	datetrunc(year,order_date) as order_date,
	sum(sales_amount) as total_sales
from gold.fact_sales
where order_date is not null
group by datetrunc(year,order_date)
--order by datetrunc(month,order_date)
)t

--9. Performance Analysis (Year-over-Year, Month-over-Month)
/* Analyze the yearly performance of products by comparing their sales 
to both the average sales performance of the product and the previous year's sales */

-- step 1
select 
	f.order_date,
	p.product_name,
	f.sales_amount
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key

-- step 2
select 
	year(f.order_date) as order_year,
	p.product_name,
	sum(f.sales_amount) as current_sales
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
where f.order_date is not null
group by year(f.order_date),p.product_name

-- step 3
with yearly_product_sales as (
select 
	year(f.order_date) as order_year,
	p.product_name,
	sum(f.sales_amount) as current_sales
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
where f.order_date is not null
group by year(f.order_date),p.product_name
)
select 
	order_year,
	product_name,
	current_sales
from yearly_product_sales
order by product_name,order_year


-- step 4
with yearly_product_sales as (
select 
	year(f.order_date) as order_year,
	p.product_name,
	sum(f.sales_amount) as current_sales
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
where f.order_date is not null
group by year(f.order_date),p.product_name
)
select 
	order_year,
	product_name,
	current_sales,
	avg(current_sales) over(partition by product_name) as avg_sales
from yearly_product_sales
order by product_name,order_year

-- step 5
with yearly_product_sales as (
select 
	year(f.order_date) as order_year,
	p.product_name,
	sum(f.sales_amount) as current_sales
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
where f.order_date is not null
group by year(f.order_date),p.product_name
)
select 
	order_year,
	product_name,
	current_sales,
	avg(current_sales) over(partition by product_name) as avg_sales,
	current_sales - avg(current_sales) over(partition by product_name) as diff_avg,
	case when current_sales - avg(current_sales) over(partition by product_name) > 0 then 'above avg'
		 when current_sales - avg(current_sales) over(partition by product_name) < 0 then 'below avg'
	else 'avg'
	end as avg_change
from yearly_product_sales
order by product_name,order_year

-- step 6
with yearly_product_sales as (
select 
	year(f.order_date) as order_year,
	p.product_name,
	sum(f.sales_amount) as current_sales
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
where f.order_date is not null
group by year(f.order_date),p.product_name
)
select 
	order_year,
	product_name,
	current_sales,
	avg(current_sales) over(partition by product_name) as avg_sales,
	current_sales - avg(current_sales) over(partition by product_name) as diff_avg,
	case when current_sales - avg(current_sales) over(partition by product_name) > 0 then 'above avg'
		 when current_sales - avg(current_sales) over(partition by product_name) < 0 then 'below avg'
	else 'avg'
	end as avg_change,
	--year over year analysis
	lag(current_sales) over(partition by product_name order by order_year) as py_sales,
	current_sales - lag(current_sales) over(partition by product_name order by order_year) as diff_py,
	case when current_sales - lag(current_sales) over(partition by product_name order by order_year) > 0 then 'increase'
		when current_sales - lag(current_sales) over(partition by product_name order by order_year) < 0 then 'decrease'
		else 'no change'
	end as py_change
from yearly_product_sales
order by product_name,order_year

--10.  Part-to-Whole Analysis
-- Which categories contribute the most to overall sales?

-- step 1
select 
	p.category,
	sum(f.sales_amount) as total_sales
from gold.fact_sales as f 
left join gold.dim_products as p
on p.product_key = f.product_key
group by p.category

-- step 2
with category_sales as (
select 
	p.category,
	sum(f.sales_amount) as total_sales
from gold.fact_sales as f 
left join gold.dim_products as p
on p.product_key = f.product_key
group by p.category
)
select
	category,
	total_sales,
	sum(total_sales) over() as overall_sales,
	concat(round((cast (total_sales as float)/ sum(total_sales) over())*100,2),'%') as percentage_total
from category_sales
order by total_sales desc

--11.  Data Segmentation Analysis

/*Segment products into cost ranges and 
count how many products fall into each segment*/

-- step 1
select 
	product_key,
	product_name,
	cost
from gold.dim_products

-- step 2
select 
	product_key,
	product_name,
	cost,
	case when cost < 100 then 'below 100'
		 when cost between 100 and 500 then '100-500'
		 when cost between 500 and  1000 then '500-1000'
	else 'above 1000'
	end as cost_range
from gold.dim_products

-- step 3
with product_segments as(
select 
	product_key,
	product_name,
	cost,
	case when cost < 100 then 'below 100'
		 when cost between 100 and 500 then '100-500'
		 when cost between 500 and  1000 then '500-1000'
	else 'above 1000'
	end as cost_range
from gold.dim_products
)
select 
	cost_range,
	count(product_key) as total_products
from product_segments
group by cost_range
order by total_products desc

/*Group customers into three segments based on their spending behavior:
	- VIP: Customers with at least 12 months of history and spending more than €5,000.
	- Regular: Customers with at least 12 months of history but spending €5,000 or less.
	- New: Customers with a lifespan less than 12 months.
And find the total number of customers by each group
*/

-- step 1
select c.customer_key,f.sales_amount,f.order_date
from gold.fact_sales as f
left join gold.dim_customers as c
on c.customer_key = f.customer_key

-- step 2
with customer_spending as (
select 
	c.customer_key,
	sum(f.sales_amount) as total_spending,
	min(f.order_date) as first_order,
	max(f.order_date) as last_order,
	datediff(month,min(f.order_date),max(f.order_date)) as lifespan
from gold.fact_sales as f
left join gold.dim_customers as c
on c.customer_key = f.customer_key
group by c.customer_key
)
select 
	customer_segment,
	count(customer_key) as total_customers
from (select
	customer_key,
	total_spending,
	lifespan,
	case WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
         WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'Regular'
         ELSE 'New'
    END AS customer_segment
from customer_spending
) t
group by customer_segment
order by total_customers desc